# Generated by Django 4.2.4 on 2023-12-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationmodel',
            name='image',
            field=models.ImageField(default='images/default_product.png', upload_to='images/'),
        ),
    ]
