# Generated by Django 4.2.4 on 2023-12-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_destinationmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationmodel',
            name='image',
            field=models.ImageField(blank=True, default='images/default_product.png', null=True, upload_to='images/'),
        ),
    ]
