# Generated by Django 4.2.4 on 2024-02-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_alter_destinationmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationmodel',
            name='airport',
            field=models.CharField(max_length=100, verbose_name='Aeropuerto'),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='country',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='image',
            field=models.ImageField(blank=True, default='images/default_product.png', null=True, upload_to='images/', verbose_name='Imagen'),
        ),
    ]
