databases:
  - name: listenerdb
    databaseName: listnerdb
    user: listenerdb

services:
  - type: web
    plan: free
    name: airlines
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn airlines.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: listenerdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4