# Generated by Django 4.2.4 on 2024-12-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
