# Generated by Django 4.2.4 on 2024-12-13 05:35

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_configmodel_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaletteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="Nombre de referencia de la paleta",
                        max_length=128,
                        verbose_name="Nombre de la paleta",
                    ),
                ),
                (
                    "primary_colour",
                    colorfield.fields.ColorField(
                        default="#ffffff",
                        help_text="Color para las tarjetas y/o fondos",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Color Primario",
                    ),
                ),
                (
                    "secondary_colour",
                    colorfield.fields.ColorField(
                        default="#000000",
                        help_text="Color para los botones",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Color Secundario",
                    ),
                ),
                (
                    "terciary_colour",
                    colorfield.fields.ColorField(
                        default="#FFF000",
                        help_text="Color para las fuentes de texto",
                        image_field=None,
                        max_length=25,
                        samples=None,
                        verbose_name="Color Terciario",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="palettemodel",
            constraint=models.UniqueConstraint(
                fields=(
                    "name",
                    "primary_colour",
                    "secondary_colour",
                    "terciary_colour",
                ),
                name="existing_palette",
            ),
        ),
        migrations.AddField(
            model_name="configmodel",
            name="palette",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="config_palette",
                to="config.palettemodel",
            ),
        ),
    ]
