# Generated by Django 4.2.4 on 2024-12-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_palettemodel_palettemodel_existing_palette_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="palettemodel",
            options={
                "verbose_name": "Paleta de Colores",
                "verbose_name_plural": "Paletas de Colores",
            },
        ),
    ]
