# Generated by Django 4.2.4 on 2025-08-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "title_es",
                    models.CharField(max_length=200, null=True, verbose_name="title"),
                ),
                (
                    "title_en",
                    models.CharField(max_length=200, null=True, verbose_name="title"),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("content", models.TextField(verbose_name="content")),
                ("content_es", models.TextField(null=True, verbose_name="content")),
                ("content_en", models.TextField(null=True, verbose_name="content")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="news/", verbose_name="image"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="is_featured"),
                ),
                (
                    "published",
                    models.BooleanField(default=True, verbose_name="published"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="start_date"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end_date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated_at"),
                ),
            ],
            options={
                "verbose_name": "news_sing",
                "verbose_name_plural": "news_pl",
                "ordering": ["-created_at"],
            },
        ),
    ]
